version: '3.8'

services:
  app:
    build:
      context: ./backend 
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@db:5432/cinemaplus_db
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cinemaplus_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
